---
- name: First Playbook
  hosts: all
  become: yes
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Start httpd
      service:
        name: httpd
        state: started

    - name: Copying the files
      copy:
        src: index.html
        dest: /var/www/html/index.html
      notify: Restart web server

  