---
- name: Install and start Nginx
  hosts: all
  become: yes
  tasks:
    - name:install nginx
      yum:
        name: nginx
        state: present
        update_cache: yes

    - name: nginx start
      service:
        name: nginx
        state: started
        enabled: yes