---
- name: Example Playbook with Variables
  hosts: servers
  become: yes

  vars:
    web_package: httpd
    web_service: httpd
    source_file: index.html
    dest_file: /var/www/html/index.html

  tasks:
    - name: Install web package
      yum:
        name: "{{ web_package }}"
        state: present

    - name: Start web service
      service:
        name: "{{ web_service }}"
        state: started

    - name: Copy the web file
      copy:
        src: "{{ source_file }}"
        dest: "{{ dest_file }}"
      notify: Restart web server

  handlers:
    - name: Restart web server
      service:
        name: "{{ web_service }}"
        state: restarted